version: '3.9'

services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    expose:
      - "5432"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  searxng:
    extends:
      file: ./searxng/compose.yaml
      service: searxng
  playwright-service:
    extends:
      file: ./firecrawl/docker-compose.yaml
      service: playwright-service
  firecrawl-api:
    extends:
      file: ./firecrawl/docker-compose.yaml
      service: api
  firecrawl-worker:
    extends:
      file: ./firecrawl/docker-compose.yaml
      service: worker
  redis:
    extends:
      file: ./firecrawl/docker-compose.yaml
      service: redis

networks:
  backend:
    driver: bridge
