version: '3.9'

services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
  api:
    build: .
    ports:
      - "8000:8000"
