version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5556:5556"
    links:
      - postgres
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  backend:
    driver: bridge
