import type { Metadata } from "next";
import "./globals.css";
import TanStackProvider from "@/providers/TanStackProvider";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/theme-provider"
import SideNav from "@/components/side-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanStackProvider>
            <TooltipProvider>
              <div className="h-screen w-full flex">
                <SideNav />
                {children}
              </div>
            </TooltipProvider>
          </TanStackProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
