version: '3'

services:
  searxng:
    image: searxng/searxng
    container_name: my-instance
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=my-instance
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped